// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Cpu$GameboyEmulator = require("../src/Cpu.bs.js");
var Gpu$GameboyEmulator = require("../src/Gpu.bs.js");
var Mmu$GameboyEmulator = require("../src/Mmu.bs.js");

Jest.describe("Cpu", (function (param) {
        Jest.describe("Flags", (function (param) {
                Jest.testAll("Setting flags", /* :: */[
                      /* tuple */[
                        /* Z */0,
                        128
                      ],
                      /* :: */[
                        /* tuple */[
                          /* N */1,
                          64
                        ],
                        /* :: */[
                          /* tuple */[
                            /* H */2,
                            32
                          ],
                          /* :: */[
                            /* tuple */[
                              /* C */3,
                              16
                            ],
                            /* [] */0
                          ]
                        ]
                      ]
                    ], (function (param) {
                        var flag = param[0];
                        var cpu = (function (eta) {
                              var param = undefined;
                              var param$1 = eta;
                              return Cpu$GameboyEmulator.setFlag(flag, 1, param, param$1);
                            })(Cpu$GameboyEmulator.make(/* () */0));
                        return Jest.Expect[/* toBe */2](param[1], Jest.Expect[/* expect */0](Cpu$GameboyEmulator.getFlag(flag, cpu)));
                      }));
                return Jest.test("Setting a flag with an initial value", (function (param) {
                              var cpu = Cpu$GameboyEmulator.setFlag(/* Z */0, 1, 16, Cpu$GameboyEmulator.make(/* () */0));
                              return Jest.Expect[/* toBe */2](144, Jest.Expect[/* expect */0](cpu[/* registers */1][/* f */7]));
                            }));
              }));
        return Jest.describe("Ops", (function (param) {
                      Jest.describe("Increment", (function (param) {
                              var makeState = function ($staropt$star, $staropt$star$1, $staropt$star$2, $staropt$star$3, $staropt$star$4, param) {
                                var a = $staropt$star !== undefined ? $staropt$star : 0;
                                var b = $staropt$star$1 !== undefined ? $staropt$star$1 : 0;
                                var c = $staropt$star$2 !== undefined ? $staropt$star$2 : 0;
                                var d = $staropt$star$3 !== undefined ? $staropt$star$3 : 0;
                                var e = $staropt$star$4 !== undefined ? $staropt$star$4 : 0;
                                var cpu = Cpu$GameboyEmulator.make(/* () */0);
                                var partial_arg = e;
                                var partial_arg$1 = d;
                                var partial_arg$2 = c;
                                var partial_arg$3 = b;
                                var partial_arg$4 = a;
                                var cpu$1 = (function (eta) {
                                      var param = undefined;
                                      var param$1 = undefined;
                                      var param$2 = undefined;
                                      var param$3 = eta;
                                      return Cpu$GameboyEmulator.setRegisters(partial_arg$4, partial_arg$3, partial_arg$2, partial_arg$1, partial_arg, param, param$1, param$2, param$3);
                                    })(cpu);
                                var mmu = Mmu$GameboyEmulator.load(Caml_array.caml_make_vect(4096, 0));
                                var gpu = Gpu$GameboyEmulator.make(/* () */0);
                                return /* tuple */[
                                        cpu$1,
                                        mmu,
                                        gpu
                                      ];
                              };
                              Jest.describe("INC B", (function (param) {
                                      Jest.test("increments register b", (function (param) {
                                              var match = makeState(undefined, 9, undefined, undefined, undefined, /* () */0);
                                              var cpu1 = Curry._1(Cpu$GameboyEmulator.Ops[/* Increment8 */8][/* inc_b */2], /* record */[
                                                      /* cpu */match[0],
                                                      /* mmu */match[1],
                                                      /* gpu */match[2]
                                                    ])[/* cpu */0];
                                              return Jest.Expect[/* toEqual */12](10, Jest.Expect[/* expect */0](cpu1[/* registers */1][/* b */1]));
                                            }));
                                      return Jest.test("updates the carry flag", (function (param) {
                                                    var match = makeState(undefined, 255, undefined, undefined, undefined, /* () */0);
                                                    var cpu1 = Curry._1(Cpu$GameboyEmulator.Ops[/* Increment8 */8][/* inc_b */2], /* record */[
                                                            /* cpu */match[0],
                                                            /* mmu */match[1],
                                                            /* gpu */match[2]
                                                          ])[/* cpu */0];
                                                    return Jest.Expect[/* toEqual */12](/* tuple */[
                                                                0,
                                                                128
                                                              ], Jest.Expect[/* expect */0](/* tuple */[
                                                                    cpu1[/* registers */1][/* b */1],
                                                                    cpu1[/* registers */1][/* f */7]
                                                                  ]));
                                                  }));
                                    }));
                              Jest.describe("INC C", (function (param) {
                                      Jest.test("increments register c", (function (param) {
                                              var match = makeState(undefined, undefined, 9, undefined, undefined, /* () */0);
                                              var cpu1 = Curry._1(Cpu$GameboyEmulator.Ops[/* Increment8 */8][/* inc_c */3], /* record */[
                                                      /* cpu */match[0],
                                                      /* mmu */match[1],
                                                      /* gpu */match[2]
                                                    ])[/* cpu */0];
                                              return Jest.Expect[/* toEqual */12](10, Jest.Expect[/* expect */0](cpu1[/* registers */1][/* c */2]));
                                            }));
                                      return Jest.test("updates the carry flag", (function (param) {
                                                    var match = makeState(undefined, undefined, 255, undefined, undefined, /* () */0);
                                                    var cpu1 = Curry._1(Cpu$GameboyEmulator.Ops[/* Increment8 */8][/* inc_c */3], /* record */[
                                                            /* cpu */match[0],
                                                            /* mmu */match[1],
                                                            /* gpu */match[2]
                                                          ])[/* cpu */0];
                                                    return Jest.Expect[/* toEqual */12](/* tuple */[
                                                                0,
                                                                128
                                                              ], Jest.Expect[/* expect */0](/* tuple */[
                                                                    cpu1[/* registers */1][/* c */2],
                                                                    cpu1[/* registers */1][/* f */7]
                                                                  ]));
                                                  }));
                                    }));
                              Jest.test("INC BC", (function (param) {
                                      var match = makeState(undefined, undefined, 255, undefined, undefined, /* () */0);
                                      var cpu1 = Curry._1(Cpu$GameboyEmulator.Ops[/* Increment16 */7][/* inc_bc */0], /* record */[
                                              /* cpu */match[0],
                                              /* mmu */match[1],
                                              /* gpu */match[2]
                                            ])[/* cpu */0];
                                      return Jest.Expect[/* toEqual */12](/* tuple */[
                                                  256,
                                                  1,
                                                  0
                                                ], Jest.Expect[/* expect */0](/* tuple */[
                                                      Cpu$GameboyEmulator.rBc(cpu1),
                                                      cpu1[/* registers */1][/* b */1],
                                                      cpu1[/* registers */1][/* c */2]
                                                    ]));
                                    }));
                              Jest.test("INC DE", (function (param) {
                                      var eta = Cpu$GameboyEmulator.make(/* () */0);
                                      var cpu = Curry._4((function (param, param$1, param$2, param$3) {
                                                return Curry._5(Cpu$GameboyEmulator.setRegisters, param, param$1, param$2, param$3, 255);
                                              })(undefined, undefined, undefined, undefined), undefined, undefined, undefined, eta);
                                      var mmu = Mmu$GameboyEmulator.load(Caml_array.caml_make_vect(4096, 0));
                                      var gpu = Gpu$GameboyEmulator.make(/* () */0);
                                      var cpu1 = Curry._1(Cpu$GameboyEmulator.Ops[/* Increment16 */7][/* inc_de */1], /* record */[
                                              /* cpu */cpu,
                                              /* mmu */mmu,
                                              /* gpu */gpu
                                            ])[/* cpu */0];
                                      return Jest.Expect[/* toEqual */12](/* tuple */[
                                                  256,
                                                  1,
                                                  0
                                                ], Jest.Expect[/* expect */0](/* tuple */[
                                                      Cpu$GameboyEmulator.rDe(cpu1),
                                                      cpu1[/* registers */1][/* d */3],
                                                      cpu1[/* registers */1][/* e */4]
                                                    ]));
                                    }));
                              return Jest.test("INC HL", (function (param) {
                                            var eta = Cpu$GameboyEmulator.make(/* () */0);
                                            var cpu = Curry._2((function (param, param$1, param$2, param$3, param$4, param$5) {
                                                      return Curry._7(Cpu$GameboyEmulator.setRegisters, param, param$1, param$2, param$3, param$4, param$5, 255);
                                                    })(undefined, undefined, undefined, undefined, undefined, undefined), undefined, eta);
                                            var mmu = Mmu$GameboyEmulator.load(Caml_array.caml_make_vect(4096, 0));
                                            var gpu = Gpu$GameboyEmulator.make(/* () */0);
                                            var cpu1 = Curry._1(Cpu$GameboyEmulator.Ops[/* Increment16 */7][/* inc_hl */2], /* record */[
                                                    /* cpu */cpu,
                                                    /* mmu */mmu,
                                                    /* gpu */gpu
                                                  ])[/* cpu */0];
                                            return Jest.Expect[/* toEqual */12](/* tuple */[
                                                        256,
                                                        1,
                                                        0
                                                      ], Jest.Expect[/* expect */0](/* tuple */[
                                                            Cpu$GameboyEmulator.rHl(cpu1),
                                                            cpu1[/* registers */1][/* h */5],
                                                            cpu1[/* registers */1][/* l */6]
                                                          ]));
                                          }));
                            }));
                      Jest.describe("Decrement", (function (param) {
                              Jest.test("DEC BC", (function (param) {
                                      var eta = Cpu$GameboyEmulator.make(/* () */0);
                                      var cpu = Curry._6((function (param) {
                                                return Curry._3(Cpu$GameboyEmulator.setRegisters, param, 1, 0);
                                              })(undefined), undefined, undefined, undefined, undefined, undefined, eta);
                                      var mmu = Mmu$GameboyEmulator.load(Caml_array.caml_make_vect(4096, 0));
                                      var gpu = Gpu$GameboyEmulator.make(/* () */0);
                                      var cpu1 = Curry._1(Cpu$GameboyEmulator.Ops[/* Decrement16 */12][/* dec_bc */0], /* record */[
                                              /* cpu */cpu,
                                              /* mmu */mmu,
                                              /* gpu */gpu
                                            ])[/* cpu */0];
                                      return Jest.Expect[/* toEqual */12](/* tuple */[
                                                  255,
                                                  0,
                                                  255
                                                ], Jest.Expect[/* expect */0](/* tuple */[
                                                      Cpu$GameboyEmulator.rBc(cpu1),
                                                      cpu1[/* registers */1][/* b */1],
                                                      cpu1[/* registers */1][/* c */2]
                                                    ]));
                                    }));
                              Jest.test("DEC DE", (function (param) {
                                      var eta = Cpu$GameboyEmulator.make(/* () */0);
                                      var cpu = Curry._4((function (param, param$1, param$2) {
                                                return Curry._5(Cpu$GameboyEmulator.setRegisters, param, param$1, param$2, 1, 0);
                                              })(undefined, undefined, undefined), undefined, undefined, undefined, eta);
                                      var mmu = Mmu$GameboyEmulator.load(Caml_array.caml_make_vect(4096, 0));
                                      var gpu = Gpu$GameboyEmulator.make(/* () */0);
                                      var cpu1 = Curry._1(Cpu$GameboyEmulator.Ops[/* Decrement16 */12][/* dec_de */1], /* record */[
                                              /* cpu */cpu,
                                              /* mmu */mmu,
                                              /* gpu */gpu
                                            ])[/* cpu */0];
                                      return Jest.Expect[/* toEqual */12](/* tuple */[
                                                  255,
                                                  0,
                                                  255
                                                ], Jest.Expect[/* expect */0](/* tuple */[
                                                      Cpu$GameboyEmulator.rDe(cpu1),
                                                      cpu1[/* registers */1][/* d */3],
                                                      cpu1[/* registers */1][/* e */4]
                                                    ]));
                                    }));
                              return Jest.test("DEC HL", (function (param) {
                                            var eta = Cpu$GameboyEmulator.make(/* () */0);
                                            var cpu = Curry._2((function (param, param$1, param$2, param$3, param$4) {
                                                      return Curry._7(Cpu$GameboyEmulator.setRegisters, param, param$1, param$2, param$3, param$4, 1, 0);
                                                    })(undefined, undefined, undefined, undefined, undefined), undefined, eta);
                                            var mmu = Mmu$GameboyEmulator.load(Caml_array.caml_make_vect(4096, 0));
                                            var gpu = Gpu$GameboyEmulator.make(/* () */0);
                                            var cpu1 = Curry._1(Cpu$GameboyEmulator.Ops[/* Decrement16 */12][/* dec_hl */2], /* record */[
                                                    /* cpu */cpu,
                                                    /* mmu */mmu,
                                                    /* gpu */gpu
                                                  ])[/* cpu */0];
                                            return Jest.Expect[/* toEqual */12](/* tuple */[
                                                        255,
                                                        0,
                                                        255
                                                      ], Jest.Expect[/* expect */0](/* tuple */[
                                                            Cpu$GameboyEmulator.rHl(cpu1),
                                                            cpu1[/* registers */1][/* h */5],
                                                            cpu1[/* registers */1][/* l */6]
                                                          ]));
                                          }));
                            }));
                      return Jest.testAll("RLCA", /* :: */[
                                  /* tuple */[
                                    136,
                                    17,
                                    16
                                  ],
                                  /* :: */[
                                    /* tuple */[
                                      255,
                                      255,
                                      16
                                    ],
                                    /* :: */[
                                      /* tuple */[
                                        1,
                                        2,
                                        0
                                      ],
                                      /* [] */0
                                    ]
                                  ]
                                ], (function (param) {
                                    var partial_arg = param[0];
                                    var cpu = (function (eta) {
                                          var param = undefined;
                                          var param$1 = undefined;
                                          var param$2 = undefined;
                                          var param$3 = undefined;
                                          var param$4 = undefined;
                                          var param$5 = undefined;
                                          var param$6 = undefined;
                                          var param$7 = eta;
                                          return Cpu$GameboyEmulator.setRegisters(partial_arg, param, param$1, param$2, param$3, param$4, param$5, param$6, param$7);
                                        })(Cpu$GameboyEmulator.make(/* () */0));
                                    var mmu = Mmu$GameboyEmulator.load(Caml_array.caml_make_vect(4096, 0));
                                    var gpu = Gpu$GameboyEmulator.make(/* () */0);
                                    var cpu1 = Curry._1(Cpu$GameboyEmulator.Ops[/* Rotation */13][/* rlca */0], /* record */[
                                            /* cpu */cpu,
                                            /* mmu */mmu,
                                            /* gpu */gpu
                                          ])[/* cpu */0];
                                    return Jest.Expect[/* toEqual */12](/* tuple */[
                                                param[1],
                                                param[2]
                                              ], Jest.Expect[/* expect */0](/* tuple */[
                                                    cpu1[/* registers */1][/* a */0],
                                                    Cpu$GameboyEmulator.getFlag(/* C */3, cpu1)
                                                  ]));
                                  }));
                    }));
      }));

/*  Not a pure module */
