// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Printf = require("bs-platform/lib/js/printf.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var UnhandledInstruction = Caml_exceptions.create("Cpu-GameboyEmulator.UnhandledInstruction");

var AssertionException = Caml_exceptions.create("Cpu-GameboyEmulator.AssertionException");

function flagOffset(flag) {
  switch (flag) {
    case /* Z */0 :
        return 7;
    case /* N */1 :
        return 6;
    case /* H */2 :
        return 5;
    case /* C */3 :
        return 4;
    
  }
}

function setFlag(flag, value, flags) {
  var bit = (1 << flagOffset(flag));
  if (value !== 0) {
    return flags | bit;
  } else {
    return flags & Pervasives.lnot(bit);
  }
}

function getFlag(flag, flags) {
  var offset = flagOffset(flag);
  var flag$1 = flags & (1 << offset);
  return (flag$1 >>> offset) | 0;
}

function isSet(flag, flags) {
  var offset = flagOffset(flag);
  return (flags & (1 << offset)) > 0;
}

var Flags = {
  z: 7,
  n: 6,
  h: 5,
  c: 4,
  flagOffset: flagOffset,
  setFlag: setFlag,
  getFlag: getFlag,
  isSet: isSet
};

function make(param) {
  return /* record */[
          /* clock */0,
          /* halt */0,
          /* registers : record */[
            /* a */0,
            /* b */0,
            /* c */0,
            /* d */0,
            /* e */0,
            /* h */0,
            /* l */0,
            /* f */0,
            /* sp */0,
            /* pc */0,
            /* mCycles */0
          ]
        ];
}

function b2i(bool) {
  if (bool) {
    return 1;
  } else {
    return 0;
  }
}

function programCount(cpu) {
  return cpu[/* registers */2][/* pc */9];
}

function readAndIncrementPc(cpu) {
  var match = cpu[/* registers */2];
  var pc = match[/* pc */9];
  cpu[/* registers */2][/* pc */9] = cpu[/* registers */2][/* pc */9] + 1 | 0;
  return /* tuple */[
          pc,
          cpu
        ];
}

function readRegister16(register, param) {
  var match = param[/* registers */2];
  var a = match[/* a */0];
  var b = match[/* b */1];
  var c = match[/* c */2];
  var d = match[/* d */3];
  var e = match[/* e */4];
  var h = match[/* h */5];
  var l = match[/* l */6];
  var f = match[/* f */7];
  var match$1;
  switch (register) {
    case /* AF */0 :
        match$1 = /* tuple */[
          a,
          f
        ];
        break;
    case /* BC */1 :
        match$1 = /* tuple */[
          b,
          c
        ];
        break;
    case /* DE */2 :
        match$1 = /* tuple */[
          d,
          e
        ];
        break;
    case /* HL */3 :
        match$1 = /* tuple */[
          h,
          l
        ];
        break;
    
  }
  return match$1[1] + (match$1[0] << 8) | 0;
}

function rAf(param) {
  return readRegister16(/* AF */0, param);
}

function rBc(param) {
  return readRegister16(/* BC */1, param);
}

function rDe(param) {
  return readRegister16(/* DE */2, param);
}

function rHl(param) {
  return readRegister16(/* HL */3, param);
}

function checkRegister(register) {
  if (register > 255) {
    throw [
          AssertionException,
          String(register)
        ];
  } else {
    return 0;
  }
}

function setRegisters(a, b, c, d, e, h, l, f, cpu) {
  var registers = cpu[/* registers */2];
  registers[/* a */0] = Belt_Option.getWithDefault(a, registers[/* a */0]);
  registers[/* b */1] = Belt_Option.getWithDefault(b, registers[/* b */1]);
  registers[/* c */2] = Belt_Option.getWithDefault(c, registers[/* c */2]);
  registers[/* d */3] = Belt_Option.getWithDefault(d, registers[/* d */3]);
  registers[/* e */4] = Belt_Option.getWithDefault(e, registers[/* e */4]);
  registers[/* h */5] = Belt_Option.getWithDefault(h, registers[/* h */5]);
  registers[/* l */6] = Belt_Option.getWithDefault(l, registers[/* l */6]);
  registers[/* f */7] = Belt_Option.getWithDefault(f, registers[/* f */7]);
  checkRegister(registers[/* a */0]);
  checkRegister(registers[/* b */1]);
  checkRegister(registers[/* c */2]);
  checkRegister(registers[/* d */3]);
  checkRegister(registers[/* e */4]);
  checkRegister(registers[/* h */5]);
  checkRegister(registers[/* l */6]);
  return cpu;
}

function writeRegister16(register, value, cpu) {
  if (value > 65535) {
    throw [
          AssertionException,
          Curry._1(Printf.sprintf(/* Format */[
                    /* String_literal */Block.__(11, [
                        "writeRegister16 ",
                        /* Int */Block.__(4, [
                            /* Int_d */0,
                            /* No_padding */0,
                            /* No_precision */0,
                            /* End_of_format */0
                          ])
                      ]),
                    "writeRegister16 %d"
                  ]), value)
        ];
  }
  var r1 = (value >>> 8) & 255;
  var r2 = value & 255;
  switch (register) {
    case /* AF */0 :
        var arg = r2;
        var arg$1 = function (param, param$1, param$2, param$3, param$4, param$5) {
          var partial_arg = r1;
          return (function (param$6) {
              return setRegisters(partial_arg, param, param$1, param$2, param$3, param$4, param$5, arg, param$6);
            });
        };
        return (function (eta) {
                    return arg$1(undefined, undefined, undefined, undefined, undefined, undefined)(eta);
                  })(cpu);
    case /* BC */1 :
        var arg$2 = r1;
        var arg$3 = r2;
        return (function (param) {
                      return (function (param$1, param$2, param$3, param$4, param$5, param$6) {
                          return setRegisters(param, arg$2, arg$3, param$1, param$2, param$3, param$4, param$5, param$6);
                        });
                    })(undefined)(undefined, undefined, undefined, undefined, undefined, cpu);
    case /* DE */2 :
        var arg$4 = r1;
        var arg$5 = r2;
        return (function (param, param$1, param$2) {
                      return (function (param$3, param$4, param$5, param$6) {
                          return setRegisters(param, param$1, param$2, arg$4, arg$5, param$3, param$4, param$5, param$6);
                        });
                    })(undefined, undefined, undefined)(undefined, undefined, undefined, cpu);
    case /* HL */3 :
        var arg$6 = r1;
        var arg$7 = r2;
        return (function (param, param$1, param$2, param$3, param$4) {
                      return (function (param$5, param$6) {
                          return setRegisters(param, param$1, param$2, param$3, param$4, arg$6, arg$7, param$5, param$6);
                        });
                    })(undefined, undefined, undefined, undefined, undefined)(undefined, cpu);
    
  }
}

function wHl(param, param$1) {
  return writeRegister16(/* HL */3, param, param$1);
}

function incrementPc(cycles, cpu) {
  cpu[/* registers */2][/* pc */9] = cpu[/* registers */2][/* pc */9] + cycles | 0;
  return cpu;
}

function setPc(pc, cpu) {
  cpu[/* registers */2][/* pc */9] = pc;
  return cpu;
}

function incrementSp($staropt$star, cpu) {
  var amount = $staropt$star !== undefined ? $staropt$star : 1;
  cpu[/* registers */2][/* sp */8] = cpu[/* registers */2][/* sp */8] + amount & 65535;
  return cpu;
}

function decrementSp($staropt$star, cpu) {
  var amount = $staropt$star !== undefined ? $staropt$star : 1;
  cpu[/* registers */2][/* sp */8] = cpu[/* registers */2][/* sp */8] - amount & 65535;
  return cpu;
}

function setSp(sp, cpu) {
  cpu[/* registers */2][/* sp */8] = sp & 65535;
  return cpu;
}

function getFlag$1(flag, cpu) {
  var bit = (1 << flagOffset(flag));
  return cpu[/* registers */2][/* f */7] & bit;
}

function setFlag$1(flag, value, initialValue, cpu) {
  cpu[/* registers */2][/* f */7] = setFlag(flag, value, Belt_Option.getWithDefault(initialValue, cpu[/* registers */2][/* f */7]));
  return cpu;
}

function toggleFlag(flag, cpu) {
  var flagValue = getFlag(flag, cpu[/* registers */2][/* f */7]) === 0 ? 1 : 0;
  var f = setFlag(flag, flagValue, cpu[/* registers */2][/* f */7]);
  var arg = f;
  return (function (param, param$1, param$2, param$3, param$4, param$5, param$6) {
                return (function (param$7) {
                    return setRegisters(param, param$1, param$2, param$3, param$4, param$5, param$6, arg, param$7);
                  });
              })(undefined, undefined, undefined, undefined, undefined, undefined, undefined)(cpu);
}

function machineCycles(cycles, cpu) {
  cpu[/* registers */2][/* mCycles */10] = cycles;
  return cpu;
}

function cycles(cycles$1, cpu) {
  return machineCycles(cycles$1 / 4 | 0, cpu);
}

function incrementHl(cpu) {
  var l = cpu[/* registers */2][/* l */6] + 1 & 255;
  var h = l === 0 ? cpu[/* registers */2][/* h */5] + 1 & 255 : cpu[/* registers */2][/* h */5];
  var arg = h;
  var arg$1 = l;
  return (function (param, param$1, param$2, param$3, param$4) {
                return (function (param$5, param$6) {
                    return setRegisters(param, param$1, param$2, param$3, param$4, arg, arg$1, param$5, param$6);
                  });
              })(undefined, undefined, undefined, undefined, undefined)(undefined, cpu);
}

function decrementHl(cpu) {
  var l = cpu[/* registers */2][/* l */6] - 1 & 255;
  var h = l === 255 ? cpu[/* registers */2][/* h */5] - 1 & 255 : cpu[/* registers */2][/* h */5];
  var arg = h;
  var arg$1 = l;
  return (function (param, param$1, param$2, param$3, param$4) {
                return (function (param$5, param$6) {
                    return setRegisters(param, param$1, param$2, param$3, param$4, arg, arg$1, param$5, param$6);
                  });
              })(undefined, undefined, undefined, undefined, undefined)(undefined, cpu);
}

function signed(value) {
  var match = value > 127;
  if (match) {
    return -(Pervasives.lnot(value) + 1 & 255) | 0;
  } else {
    return value;
  }
}

exports.UnhandledInstruction = UnhandledInstruction;
exports.AssertionException = AssertionException;
exports.Flags = Flags;
exports.make = make;
exports.b2i = b2i;
exports.programCount = programCount;
exports.readAndIncrementPc = readAndIncrementPc;
exports.readRegister16 = readRegister16;
exports.rAf = rAf;
exports.rBc = rBc;
exports.rDe = rDe;
exports.rHl = rHl;
exports.checkRegister = checkRegister;
exports.setRegisters = setRegisters;
exports.writeRegister16 = writeRegister16;
exports.wHl = wHl;
exports.incrementPc = incrementPc;
exports.setPc = setPc;
exports.incrementSp = incrementSp;
exports.decrementSp = decrementSp;
exports.setSp = setSp;
exports.getFlag = getFlag$1;
exports.setFlag = setFlag$1;
exports.toggleFlag = toggleFlag;
exports.machineCycles = machineCycles;
exports.cycles = cycles;
exports.incrementHl = incrementHl;
exports.decrementHl = decrementHl;
exports.signed = signed;
/* No side effect */
