// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

function newState(cpu, mmu, gpu, old) {
  return /* record */[
          /* cpu */Belt_Option.getWithDefault(cpu, old[/* cpu */0]),
          /* mmu */Belt_Option.getWithDefault(mmu, old[/* mmu */1]),
          /* gpu */Belt_Option.getWithDefault(gpu, old[/* gpu */2])
        ];
}

exports.newState = newState;
/* No side effect */
