// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Cpu$GameboyEmulator = require("./Cpu.bs.js");
var Gpu$GameboyEmulator = require("./Gpu.bs.js");
var Mmu$GameboyEmulator = require("./Mmu.bs.js");
var Renderer$GameboyEmulator = require("./Renderer.bs.js");

function load(bytes) {
  console.log("Loaded, ROM length: ", bytes.length);
  var mmu = Mmu$GameboyEmulator.load(bytes);
  return /* record */[
          /* frameCount */0,
          /* fps */0,
          /* gpu */Gpu$GameboyEmulator.make(/* () */0),
          /* cpu */Cpu$GameboyEmulator.make(/* () */0),
          /* mmu */mmu,
          /* renderer */Renderer$GameboyEmulator.make(/* () */0)
        ];
}

function reset(state) {
  return /* record */[
          /* frameCount */state[/* frameCount */0] + 1 | 0,
          /* fps */0,
          /* gpu */Gpu$GameboyEmulator.make(/* () */0),
          /* cpu */state[/* cpu */3],
          /* mmu */Mmu$GameboyEmulator.reset(state[/* mmu */4]),
          /* renderer */state[/* renderer */5]
        ];
}

function frame(s) {
  var programCount = Cpu$GameboyEmulator.programCount(s[/* cpu */3]);
  var match = Mmu$GameboyEmulator.read8(programCount, /* record */[
        /* gpu */s[/* gpu */2],
        /* mmu */s[/* mmu */4]
      ]);
  var match$1 = Curry._1(Cpu$GameboyEmulator.exec(match[0]), /* record */[
        /* cpu */s[/* cpu */3],
        /* mmu */match[1],
        /* gpu */s[/* gpu */2]
      ]);
  var cpu = match$1[/* cpu */0];
  var gpu = Gpu$GameboyEmulator.step(cpu[/* registers */1][/* mCycles */10], s[/* renderer */5], s[/* gpu */2]);
  s[/* gpu */2] = gpu;
  s[/* mmu */4] = match$1[/* mmu */1];
  s[/* cpu */3] = cpu;
  s[/* cpu */3][/* clock */0] = s[/* cpu */3][/* clock */0] + cpu[/* registers */1][/* mCycles */10] | 0;
  s[/* cpu */3][/* registers */1][/* pc */9] = Cpu$GameboyEmulator.programCount(cpu) + 1 & 65535;
  return s;
}

exports.load = load;
exports.reset = reset;
exports.frame = frame;
/* Cpu-GameboyEmulator Not a pure module */
