// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Printf = require("bs-platform/lib/js/printf.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");
var Cpu$GameboyEmulator = require("./Cpu.bs.js");
var Gpu$GameboyEmulator = require("./Gpu.bs.js");
var Mmu$GameboyEmulator = require("./Mmu.bs.js");
var Cpu_ops$GameboyEmulator = require("./Cpu_ops.bs.js");
var Renderer$GameboyEmulator = require("./Renderer.bs.js");

var NoCycles = Caml_exceptions.create("Emulator-GameboyEmulator.NoCycles");

function load(bytes) {
  console.log("Loaded, ROM length: ", bytes.length);
  var mmu = Mmu$GameboyEmulator.load(bytes);
  return /* record */[
          /* frameCount */0,
          /* fps */0,
          /* gpu */Gpu$GameboyEmulator.make(/* () */0),
          /* cpu */Cpu$GameboyEmulator.make(/* () */0),
          /* mmu */mmu,
          /* renderer */Renderer$GameboyEmulator.make(/* () */0),
          /* debugInstructions : [] */0
        ];
}

function reset(state) {
  return /* record */[
          /* frameCount */state[/* frameCount */0] + 1 | 0,
          /* fps */0,
          /* gpu */Gpu$GameboyEmulator.make(/* () */0),
          /* cpu */state[/* cpu */3],
          /* mmu */Mmu$GameboyEmulator.reset(state[/* mmu */4]),
          /* renderer */state[/* renderer */5],
          /* debugInstructions */state[/* debugInstructions */6]
        ];
}

function addInstructionToDebug(s, instruction) {
  var cpu = s[/* cpu */3];
  var pc = cpu[/* registers */3][/* pc */9];
  var sp = cpu[/* registers */3][/* sp */8];
  var d = /* record */[
    /* instruction */instruction,
    /* pc */pc,
    /* sp */sp
  ];
  var debugInstructions_001 = s[/* debugInstructions */6];
  var debugInstructions = /* :: */[
    d,
    debugInstructions_001
  ];
  var debugInstructions$1 = Belt_Option.getWithDefault(Belt_List.take(debugInstructions, 50), debugInstructions);
  return /* record */[
          /* frameCount */s[/* frameCount */0],
          /* fps */s[/* fps */1],
          /* gpu */s[/* gpu */2],
          /* cpu */s[/* cpu */3],
          /* mmu */s[/* mmu */4],
          /* renderer */s[/* renderer */5],
          /* debugInstructions */debugInstructions$1
        ];
}

function execInstructionsForFrame(s, _currCycles, maxCycles) {
  while(true) {
    var currCycles = _currCycles;
    var match = Mmu$GameboyEmulator.read8(Cpu$GameboyEmulator.programCount(s[/* cpu */3]), /* record */[
          /* gpu */s[/* gpu */2],
          /* mmu */s[/* mmu */4]
        ]);
    var instruction = match[0];
    s[/* cpu */3][/* registers */3][/* pc */9] = Cpu$GameboyEmulator.programCount(s[/* cpu */3]) + 1 & 65535;
    var match$1 = Curry._1(Cpu_ops$GameboyEmulator.exec(instruction), /* record */[
          /* cpu */s[/* cpu */3],
          /* mmu */match[1],
          /* gpu */s[/* gpu */2]
        ]);
    var cpu = match$1[/* cpu */0];
    if (cpu[/* registers */3][/* mCycles */10] <= 0) {
      throw [
            NoCycles,
            Curry._1(Printf.sprintf(/* Format */[
                      /* String_literal */Block.__(11, [
                          "mCycles=0: ",
                          /* Int */Block.__(4, [
                              /* Int_x */6,
                              /* No_padding */0,
                              /* No_precision */0,
                              /* End_of_format */0
                            ])
                        ]),
                      "mCycles=0: %x"
                    ]), instruction)
          ];
    }
    var gpu = Gpu$GameboyEmulator.step(cpu[/* registers */3][/* mCycles */10], s[/* renderer */5], s[/* gpu */2]);
    s[/* gpu */2] = gpu;
    s[/* mmu */4] = match$1[/* mmu */1];
    s[/* cpu */3] = cpu;
    s[/* cpu */3][/* clock */0] = s[/* cpu */3][/* clock */0] + cpu[/* registers */3][/* mCycles */10] | 0;
    if (currCycles >= maxCycles) {
      return s;
    } else {
      _currCycles = currCycles + 1 | 0;
      continue ;
    }
  };
}

function frame(s) {
  var frameClock = s[/* cpu */3][/* clock */0] + 17556 | 0;
  return execInstructionsForFrame(s, s[/* cpu */3][/* clock */0], frameClock);
}

exports.NoCycles = NoCycles;
exports.load = load;
exports.reset = reset;
exports.addInstructionToDebug = addInstructionToDebug;
exports.execInstructionsForFrame = execInstructionsForFrame;
exports.frame = frame;
/* Gpu-GameboyEmulator Not a pure module */
