// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Utils$GameboyEmulator = require("./Utils.bs.js");
var Emulator$GameboyEmulator = require("./Emulator.bs.js");

var fpsNum = document.querySelector("#fps-num");

function loop(prevFrame, state) {
  var newState = Emulator$GameboyEmulator.frame(state);
  var time = Date.now();
  var time_ = time * (1.0 - 0.97) + prevFrame * 0.97;
  var diff = time_ - prevFrame;
  var fps = 1000 / diff;
  requestAnimationFrame((function (param) {
          return loop(time_, newState);
        }));
  fpsNum.textContent = String(Math.round(fps) | 0);
  return /* () */0;
}

Utils$GameboyEmulator.Xhr[/* openUri */1](/* GET */3546230, "../roms/cpu_instrs/cpu_instrs.gb", new XMLHttpRequest()).then((function (bytes) {
          console.log(bytes);
          return Promise.resolve(bytes);
        })).then((function (bytes) {
        return Promise.resolve(loop(Date.now(), Emulator$GameboyEmulator.load(bytes)));
      }));

var weightRatio = 0.97;

exports.fpsNum = fpsNum;
exports.weightRatio = weightRatio;
exports.loop = loop;
/* fpsNum Not a pure module */
