// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Belt_Range = require("bs-platform/lib/js/belt_Range.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Utils$GameboyEmulator = require("./Utils.bs.js");

function make(param) {
  var canvas = Curry._1(Utils$GameboyEmulator.Canvas[/* getContextFromId */0], "screen");
  var screen = canvas.createImageData(160, 144);
  var screenData = screen.data;
  $$Array.iteri((function (idx, _i) {
          return Caml_array.caml_array_set(screenData, idx, 255);
        }), screenData);
  canvas.putImageData(screen, 0, 0);
  return /* record */[
          /* canvas */canvas,
          /* screen */screen
        ];
}

function renderToScreen(renderer) {
  renderer[/* canvas */0].putImageData(renderer[/* screen */1], 0, 0);
  return /* () */0;
}

function renderScan(renderer, gpu) {
  renderer[/* screen */1].data;
  Belt_Range.forEach(0, 159, (function (i) {
          console.log(i);
          console.log(i);
          return /* () */0;
        }));
  return gpu;
}

exports.make = make;
exports.renderToScreen = renderToScreen;
exports.renderScan = renderScan;
/* Utils-GameboyEmulator Not a pure module */
