// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Cpu$GameboyEmulator = require("./Cpu.bs.js");
var Gpu$GameboyEmulator = require("./Gpu.bs.js");
var Mmu$GameboyEmulator = require("./Mmu.bs.js");
var Renderer$GameboyEmulator = require("./Renderer.bs.js");

function load(bytes) {
  console.log("Loaded, ROM length: ", bytes.length);
  var mmu = Mmu$GameboyEmulator.load(bytes);
  return /* record */[
          /* frameCount */0,
          /* fps */0,
          /* renderer */Renderer$GameboyEmulator.make(/* () */0),
          /* gpu */Gpu$GameboyEmulator.make(/* () */0),
          /* cpu */Cpu$GameboyEmulator.make(/* () */0),
          /* mmu */mmu
        ];
}

function reset(state) {
  return /* record */[
          /* frameCount */state[/* frameCount */0] + 1 | 0,
          /* fps */0,
          /* renderer */state[/* renderer */2],
          /* gpu */Gpu$GameboyEmulator.make(/* () */0),
          /* cpu */state[/* cpu */4],
          /* mmu */Mmu$GameboyEmulator.reset(state[/* mmu */5])
        ];
}

function frame(s) {
  var programCount = Cpu$GameboyEmulator.programCount(s[/* cpu */4]);
  var match = Mmu$GameboyEmulator.read8(programCount, /* record */[
        /* gpu */s[/* gpu */3],
        /* mmu */s[/* mmu */5]
      ]);
  var match$1 = Curry._1(Cpu$GameboyEmulator.exec(match[0]), /* record */[
        /* cpu */s[/* cpu */4],
        /* mmu */match[1],
        /* gpu */s[/* gpu */3]
      ]);
  var cpu = match$1[0];
  var gpu = Gpu$GameboyEmulator.step(cpu[/* registers */1][/* mCycles */10], s[/* renderer */2], s[/* gpu */3]);
  var init = cpu[/* registers */1];
  return /* record */[
          /* frameCount */s[/* frameCount */0],
          /* fps */s[/* fps */1],
          /* renderer */s[/* renderer */2],
          /* gpu */gpu,
          /* cpu : record */[
            /* clock */cpu[/* clock */0] + cpu[/* registers */1][/* mCycles */10] | 0,
            /* registers : record */[
              /* a */init[/* a */0],
              /* b */init[/* b */1],
              /* c */init[/* c */2],
              /* d */init[/* d */3],
              /* e */init[/* e */4],
              /* h */init[/* h */5],
              /* l */init[/* l */6],
              /* f */init[/* f */7],
              /* sp */init[/* sp */8],
              /* pc */Cpu$GameboyEmulator.programCount(cpu) + 1 & 65535,
              /* mCycles */init[/* mCycles */10]
            ]
          ],
          /* mmu */match$1[1]
        ];
}

exports.load = load;
exports.reset = reset;
exports.frame = frame;
/* Gpu-GameboyEmulator Not a pure module */
