// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Mmu$GameboyEmulator = require("./Mmu.bs.js");

function make() {
  return /* record */[/* i */0];
}

var Z80 = /* module */[/* make */make];

function load(bytes) {
  console.log("Loaded, ROM length: ", bytes.length);
  var mmu = Mmu$GameboyEmulator.load(bytes);
  var b = Mmu$GameboyEmulator.read8(Mmu$GameboyEmulator.load(bytes), 1);
  console.log("Byte:", b);
  return /* record */[
          /* cpu : record */[/* i */0],
          /* mmu */mmu,
          /* rom */bytes
        ];
}

function reset(state) {
  return /* record */[
          /* cpu */state[/* cpu */0],
          /* mmu */Mmu$GameboyEmulator.reset(state[/* mmu */1]),
          /* rom */state[/* rom */2]
        ];
}

function frame(s) {
  return s;
}

exports.Z80 = Z80;
exports.load = load;
exports.reset = reset;
exports.frame = frame;
/* No side effect */
