// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Utils$GameboyEmulator = require("./Utils.bs.js");

function renderToScreen(gpu) {
  gpu[/* canvas */0].putImageData(gpu[/* screen */1], 0, 0);
  return gpu;
}

function make() {
  var canvas = Curry._1(Utils$GameboyEmulator.Canvas[/* getContextFromId */0], "screen");
  var screen = canvas.createImageData(160, 144);
  var screenData = screen.data;
  $$Array.iteri((function (idx, _) {
          return Caml_array.caml_array_set(screenData, idx, 255);
        }), screenData);
  canvas.putImageData(screen, 0, 0);
  return /* record */[
          /* canvas */canvas,
          /* screen */screen,
          /* mode */0,
          /* clock */0,
          /* line */0,
          /* vram */Caml_array.caml_make_vect(8192, 0),
          /* oam */Caml_array.caml_make_vect(160, 0)
        ];
}

function reset(gpu) {
  return /* record */[
          /* canvas */gpu[/* canvas */0],
          /* screen */gpu[/* screen */1],
          /* mode */0,
          /* clock */0,
          /* line */0,
          /* vram : array */[],
          /* oam : array */[]
        ];
}

function renderScan(gpu) {
  return gpu;
}

function step(mCycles, gpu) {
  var modeclock = gpu[/* clock */3] + mCycles | 0;
  var gpu_000 = /* canvas */gpu[/* canvas */0];
  var gpu_001 = /* screen */gpu[/* screen */1];
  var gpu_002 = /* mode */gpu[/* mode */2];
  var gpu_004 = /* line */gpu[/* line */4];
  var gpu_005 = /* vram */gpu[/* vram */5];
  var gpu_006 = /* oam */gpu[/* oam */6];
  var gpu$1 = /* record */[
    gpu_000,
    gpu_001,
    gpu_002,
    /* clock */modeclock,
    gpu_004,
    gpu_005,
    gpu_006
  ];
  var match = gpu_002;
  if (match > 3 || match < 0) {
    return gpu$1;
  } else {
    switch (match) {
      case 0 : 
          if (modeclock >= 51) {
            var line = gpu_004 + 1 | 0;
            if (line === 143) {
              return renderToScreen(/* record */[
                          gpu_000,
                          gpu_001,
                          /* mode */1,
                          /* clock */0,
                          gpu_004,
                          gpu_005,
                          gpu_006
                        ]);
            } else {
              return /* record */[
                      gpu_000,
                      gpu_001,
                      /* mode */2,
                      /* clock */0,
                      gpu_004,
                      gpu_005,
                      gpu_006
                    ];
            }
          } else {
            return gpu$1;
          }
      case 1 : 
          return gpu$1;
      case 2 : 
          if (modeclock >= 20) {
            return /* record */[
                    gpu_000,
                    gpu_001,
                    /* mode */3,
                    /* clock */0,
                    gpu_004,
                    gpu_005,
                    gpu_006
                  ];
          } else {
            return gpu$1;
          }
      case 3 : 
          if (modeclock >= 43) {
            return /* record */[
                    gpu_000,
                    gpu_001,
                    /* mode */0,
                    /* clock */0,
                    gpu_004,
                    gpu_005,
                    gpu_006
                  ];
          } else {
            return gpu$1;
          }
      
    }
  }
}

exports.renderToScreen = renderToScreen;
exports.make = make;
exports.reset = reset;
exports.renderScan = renderScan;
exports.step = step;
/* Utils-GameboyEmulator Not a pure module */
