// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Utils$GameboyEmulator = require("./Utils.bs.js");

function make() {
  var canvas = Curry._1(Utils$GameboyEmulator.Canvas[/* getContextFromId */0], "screen");
  var screen = canvas.createImageData(160, 144);
  var screenData = screen.data;
  $$Array.iteri((function (idx, _) {
          return Caml_array.caml_array_set(screenData, idx, 255);
        }), screenData);
  canvas.putImageData(screen, 0, 0);
  return /* record */[
          /* canvas */canvas,
          /* screen */screen
        ];
}

function renderToScreen(renderer, gpu) {
  renderer[/* canvas */0].putImageData(renderer[/* screen */1], 0, 0);
  return gpu;
}

function renderScan(gpu) {
  return gpu;
}

exports.make = make;
exports.renderToScreen = renderToScreen;
exports.renderScan = renderScan;
/* Utils-GameboyEmulator Not a pure module */
