// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

var toArray = (function(response) { return new Uint8Array(response); });

function openUri(method__, uri, xhr) {
  return new Promise((function (resolve, _) {
                xhr.onload = (function () {
                    return resolve(Curry._1(toArray, xhr.response));
                  });
                xhr.responseType = "arraybuffer";
                xhr.open((function () {
                          switch (method__) {
                            case 3546230 : 
                                return "GET";
                            case 891112544 : 
                                return "POST";
                            
                          }
                        })(), uri, true);
                xhr.send();
                return /* () */0;
              }));
}

var Xhr = /* module */[
  /* toArray */toArray,
  /* openUri */openUri
];

var getContextFromId = (
      function(id) {
        const canvas = document.getElementById(id)
        return canvas.getContext("2d");
      }
  );

var Canvas = /* module */[/* getContextFromId */getContextFromId];

var Window = /* module */[];

exports.Xhr = Xhr;
exports.Canvas = Canvas;
exports.Window = Window;
/* toArray Not a pure module */
