// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Cpu$GameboyEmulator = require("../src/Cpu.bs.js");

describe("Cpu", (function () {
        describe("Flags", (function () {
                Jest.testAll("Setting flags", /* :: */[
                      /* tuple */[
                        /* Z */0,
                        128
                      ],
                      /* :: */[
                        /* tuple */[
                          /* N */1,
                          64
                        ],
                        /* :: */[
                          /* tuple */[
                            /* H */2,
                            32
                          ],
                          /* :: */[
                            /* tuple */[
                              /* C */3,
                              16
                            ],
                            /* [] */0
                          ]
                        ]
                      ]
                    ], (function (param) {
                        var flag = param[0];
                        var cpu = (function (eta) {
                              var param = undefined;
                              var param$1 = eta;
                              return Cpu$GameboyEmulator.setFlag(flag, 1, param, param$1);
                            })(Cpu$GameboyEmulator.make(/* () */0));
                        return Jest.Expect[/* toBe */2](param[1], Jest.Expect[/* expect */0](Cpu$GameboyEmulator.getFlag(flag, cpu)));
                      }));
                return Jest.test("Setting a flag with an initial value", (function () {
                              var cpu = Cpu$GameboyEmulator.setFlag(/* Z */0, 1, 16, Cpu$GameboyEmulator.make(/* () */0));
                              return Jest.Expect[/* toBe */2](144, Jest.Expect[/* expect */0](cpu[/* registers */1][/* f */7]));
                            }));
              }));
        return /* () */0;
      }));

/*  Not a pure module */
